name: Generate Table Of Contents

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
      # Setup
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      # Build
      - run: yarn install --skip-builds
      - name: Generate table of contents
        run: |
          cd scripts
          yarn g:tsn index.ts
          git commit -am "chore: generate TOC"
          git push
