name: Publish Brew

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Resolve
        run: swift package resolve
      - name: Build
        run: swift build
      - name: Perform package tests
        run: swift test
      - name: Integration tests with workflows
        run: |
          make update_brew
          git add .
          git commit -m ":rocket: publish brew"
          git push
