name: Publish Brew

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      # We don't perform any tests since a tag should only be made on
      # a stable branch.
      - run: |
          make update_brew
          git push origin main
